name: Change Trigger

on:

  push:

    paths:

      - '**'

  pull_request:

    paths:

      - '**'



jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

        with:

          ref: main

          repository: harshulgupt/json_pvt

          token: ${{ secrets.PAT }}

      - name: Check changes

        run: echo "Checking changes made to repository files"
