name: Execute script

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  LAL: ${{ secrets.LAL }}

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      env:
        LAL: ${{ env.LAL }}
      run: |
        #!/bin/bash
        python3 notebooks/script.py
