name: Zip copy

on:
  workflow_dispatch:

jobs:
  copy_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        with:
          source-files: "images/"
          destination-username: "harshulgupt"
          destination-repository: "workflow"
          destination-directory: "projects/my-project"
          commit-email: "harshulgupt@gmail.com"
